#!/bin/bash
# Generate daily summary report

CONFIG_FILE="$HOME/.streaming-scout/config.json"
DATA_DIR="$HOME/.streaming-scout/data"
DATE=${1:-$(date +%Y-%m-%d)}

INPUT_DIR="$DATA_DIR/$DATE"
REPORT_FILE="$INPUT_DIR/daily-report.md"

if [ ! -d "$INPUT_DIR" ]; then
    echo "ERROR: No data found for $DATE"
    exit 1
fi

echo "=== Generating Daily Report for $DATE ==="
echo ""

# Generate markdown report
cat > "$REPORT_FILE" << EOF
# Streaming Opportunity Scout - Daily Report
**Date:** $DATE

## Summary
- Total opportunities found: [COUNT]
- High intent (7+): [COUNT]
- Approved for follow-up: [COUNT]
- Rejected/Skipped: [COUNT]

## Top Opportunities

### Score 9-10 (Ready to Engage)
[High-intent opportunities with drafted responses]

### Score 7-8 (Strong Interest)
[Medium-high intent opportunities]

### Score 5-6 (Research Phase)
[Early-stage researchers]

## Trending Topics
[Recurring themes from today's scans]

## Recommended Replies (Awaiting Approval)
[Drafted responses ready for human review]

## Follow-up Reminders
[Conversations to check back on]

## Risky Conversations (Avoid)
[Complaints about specific brands, legal issues, etc.]

## Actions Taken
- [ ] Reviewed all high-score opportunities
- [ ] Approved responses for posting
- [ ] Scheduled follow-ups

---
*Report generated by Streaming Opportunity Scout*
EOF

echo "Report saved to: $REPORT_FILE"
echo ""
cat "$REPORT_FILE"